version: "3.9"
services:
  ml:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -lc "pip install jupyterlab && jupyter lab --ip=0.0.0.0 --no-browser --allow-root"