x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  user: "50000:0"
  environment:
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  volumes:
    - airflow_home:/opt/airflow
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./models:/opt/airflow/models
    - ./results:/opt/airflow/results

services:
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: -lc "
      airflow db migrate &&
      airflow users create --role Admin --username march --password madness \
        --firstname a --lastname a --email a@a.a"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports: ["8080:8080"]
    depends_on: [airflow-init]

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on: [airflow-webserver]

  airflow-cli:
    <<: *airflow-common
    entrypoint: "airflow"
    command: "info"

volumes:
  airflow_home: {}
  logs: {}
  plugins: {}
  data: {}
  models: {}
  results: {}